export db_structure

function db_structure(; )
    order = [
        ("core"      , "users"   ),
        ("core"      , "tokens"  ),
        ("core"      , "stats"   ),
        ("processing", "jobs"    ),
        ("processing", "tasks"   ),
        ("processing", "logs"    ),
        ("metadata"  , "dataset" ),
        ("metadata"  , "catalogs"),
        ("metadata"  , "coi"     ),
    ]
    structure = Dict(
        "core" => Dict(
            "users" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "name" => "TEXT",
                "email" => "TEXT",
                "role"  => "TEXT",    # su | analyst | user | viewer
                "password_hash" => "TEXT",
                "pg_role"     => "TEXT",  # PG login role: hr_u_<id>
                "pg_password" => "TEXT",  # plain password for the PG role
                "created_at" => "TIMESTAMP"
            ),
            "tokens" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "user_id" => "INTEGER REFERENCES core.users(id) ON DELETE CASCADE",
                "token_hash" => "TEXT NOT NULL",
                "created_at" => "TIMESTAMP",
                "last_used_at" => "TIMESTAMP"
            ),
            "stats" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "user_id" => "INTEGER UNIQUE NOT NULL REFERENCES core.users(id) ON DELETE CASCADE",
                "upload_bytes" => "BIGINT NOT NULL DEFAULT 0",
                "upload_count" => "INTEGER NOT NULL DEFAULT 0",
                "last_upload" => "TIMESTAMP"
            )
        ),
        "processing" => Dict(
            "jobs" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "user_id" => "INTEGER REFERENCES core.users(id) ON DELETE CASCADE",
                "dir" => "TEXT",
                "jld2_path" => "TEXT",
                "submitted_at" => "TIMESTAMP",
                "created_at" => "TIMESTAMP",
                "completed_at" => "TIMESTAMP",
                "status" => "TEXT",
                "err_msg" => "TEXT",
                "json" => "JSONB"
            ),
            "tasks" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "job_id" => "INTEGER REFERENCES processing.jobs(id) ON DELETE CASCADE",
                "name" => "TEXT",
                "status" => "TEXT",
                "percent" => "REAL",
                "step" => "TEXT",
                "started_at" => "TIMESTAMP",
                "completed_at" => "TIMESTAMP",
                "err_msg" => "TEXT"
            ),
            # Persistent log store — lets Hydrorisk replay missed SSE events on reconnect.
            # Written by JobLogger alongside each NOTIFY osmotic_log.
            # Linked to the user (not the job) so upload ops without a processing.jobs row
            # are also persisted.  job_id_hash is nullable text for filtering by operation.
            "logs" => Dict(
                "id"      => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "user_id" => "INTEGER NOT NULL REFERENCES core.users(id) ON DELETE CASCADE",
                "level"   => "TEXT",
                "msg"     => "TEXT",
                "ts"      => "TIMESTAMP DEFAULT NOW()"
            ),
        ),
        "data" => Dict(

        ),
        "metadata" => Dict(
            "dataset" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "user_id" => "INTEGER REFERENCES core.users(id) ON DELETE CASCADE",
                "data_table" => "TEXT",
                "source" => "TEXT",
                "name" => "TEXT",
                "format" => "TEXT",
                "category" => "TEXT",
                "description" => "TEXT",
                "columns" => "TEXT[]",
                "table_cols" => "TEXT[]",
                "geom" => "TEXT",
                "srid" => "INT",
                "created_at" => "TIMESTAMP",
                "timestamps" => "JSONB",
                "input"  => "BOOLEAN NOT NULL DEFAULT FALSE",
                "result" => "BOOLEAN NOT NULL DEFAULT FALSE",
                "job_id" => "INTEGER REFERENCES processing.jobs(id) ON DELETE SET NULL"
            ),
            "catalogs" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
                "id_hash" => "TEXT",
                "name" => "TEXT",
                "json" => "JSONB"
            ),
            "coi" => Dict(
                "id" => "INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY",
                "id_hash" => "TEXT",
                "user_id" => "INTEGER REFERENCES core.users(id) ON DELETE CASCADE",
                "name" => "TEXT",
                "region" => "JSONB",
                "time" => "JSONB",
                "space" => "JSONB",
            ),            
        ),# coi = (space-time) continuum of interest
    )
    return order, structure
end